// Keep FAN_CARDS but rename to CAROUSEL_CONFIG — no src/alt needed
export const CAROUSEL_CONFIG = [
  {
    skewY: 7.5,
    scale: 2,
    translateY: -10,
    rotateY: 77.5,
    zIndex: 1,
    width: "105px",
    height: 220,
    heightOffset: 5,
    mxValue: "mx-6",
    clipLeft: true,
  },
  {
    skewY: 5,
    scale: 1.55,
    translateY: 0,
    rotateY: 57.5,
    zIndex: 97.5,
    width: "115px",
    height: 220,
    heightOffset: 4,
    mxValue: "mx-4",
  },
  {
    skewY: 3,
    scale: 1.3,
    translateY: 5,
    rotateY: 37.5,
    zIndex: 3,
    width: "125px",
    height: 220,
    heightOffset: 3,
    mxValue: "mx-3",
  },
  {
    skewY: 1.5,
    scale: 1.1,
    translateY: 5,
    rotateY: 20.5,
    zIndex: 4,
    width: "135px",
    height: 220,
    heightOffset: 2,
    mxValue: "mx-2",
  },
  {
    skewY: 0,
    scale: 1,
    translateY: 5,
    rotateY: 0,
    zIndex: 98.5,
    width: "125px",
    height: 220,
    heightOffset: 1.5,
    mxValue: "mx-2",
  },
  {
    skewY: -1.5,
    scale: 1.1,
    translateY: 5,
    rotateY: -20.5,
    zIndex: 4,
    width: "135px",
    height: 220,
    heightOffset: 2,
    mxValue: "mx-2",
  },
  {
    skewY: -3,
    scale: 1.3,
    translateY: 5,
    rotateY: -37.5,
    zIndex: 3,
    width: "125px",
    height: 220,
    heightOffset: 3,
    mxValue: "mx-3",
  },
  {
    skewY: -5,
    scale: 1.55,
    translateY: 0,
    rotateY: -57.5,
    zIndex: 3,
    width: "115px",
    height: 220,
    heightOffset: 4,
    mxValue: "mx-4",
  },
  {
    skewY: -7.5,
    scale: 2,
    translateY: -10,
    rotateY: -77.5,
    zIndex: 3,
    width: "105px",
    height: 220,
    heightOffset: 5,
    mxValue: "mx-6",
  },
];
